config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :reservations, only: %i[index create] do
      resources :reviews, only: [:create]
    end
  end
  resources :reservations, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :client, class_name: "User"
  belongs_to :provider, class_name: "User"

  has_many :reviews, dependent: :delete_all

  validates :date, presence: true
  validates :date, date: true
  # validates :date, date: { after: proc { Time.now } }

  # validates :duration, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :reservation, dependent: :destroy

  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: 0..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_many :reservations, class_name: "Reservation", foreign_key: "client_id", dependent: :destroy
  has_many :services, class_name: "Reservation", foreign_key: "provider_id", dependent: :destroy
  has_many :reviews
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name, uniqueness: { scope: :first_name }

  validates :phone_number, format: { with: /0[1-9]((\s|-?)\d{2}(\s|-?)){4}/ }
  validates :location, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_first_name,
    against: [ :first_name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  pg_search_scope :search_by_service,
    against: [ :service],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number service location reward])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone_number service location reward])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    # @reservations = Reservation.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
    @next_reservations = @user.reservations.where('date >= ?', DateTime.now)
    @past_reservations = @user.reservations.where('date < ?', DateTime.now)
  end

  def create
    @reservation = Reservation.new(client: current_user,
                                   provider: User.find(params[:user_id]),
                                   date: params['reservation']['date'])
    if @reservation.save
      redirect_to user_reservations_path(@reservation.client), notice: "flash"
    else
      redirect_to user_path(@reservation.provider)
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    redirect_to user_reservations_path(@reservation.client)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    comment = params[:review][:comment]
    rating = params[:review][:rating]
    reservation = Reservation.find(params[:reservation_id])
    client = User.find(params[:user_id])
    @review = Review.new(user: client, reservation: reservation, comment: comment, rating: rating)
    if @review.save
      redirect_to user_path(reservation.provider)
    else
      redirect_to user_reservations_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_user, only: %i[show]

  def show
    @reservation = Reservation.new
    @reviews = Reservation.where(provider: @user).map(&:reviews).flatten
  end

  def index
    if params[:provider].present?
      @users = User.search_by_first_name(params[:provider])
    elsif params[:location].present? && params[:service].present?
      @users = User.near(params[:location]).search_by_service(params[:service])
    elsif params[:service].present?
      @users = User.search_by_service(params[:service])
    elsif params[:location].present?
      @users = User.near(params[:location])
    else
      @users = User.all
    end

    @users = @users.select do |user|
      user != current_user
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlumniAndFriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/index.html.erb
<%= render 'shared/navbar' %>
<div class="reservation-layout">
  <h1>Mes réservations</h1>
  <h2>Prochaines réservations:</h2>
    <% @next_reservations.each do |next_reservation| %>
      <div class="card-reservation">
        <div class="info-reservation">
          <strong>prochaine réservation avec <%= next_reservation.provider.first_name %></strong>
          <p>Le <%= next_reservation.date %> à <%= next_reservation.provider.location %> </p>
          <%= link_to "annuler", reservation_path(next_reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: "btn-reservation" %>
        </div>
      </div>
    <% end %>

  <h2>Anciennes réservations:</h2>
  <% @past_reservations.each do |past_reservation| %>
    <div data-controller="comment">
      <% review = Review.new %>
        <div class="card-reservation">
          <div class="info-reservation">
            <strong> Ancienne réservation avec <%= link_to(past_reservation.provider.first_name, user_path(past_reservation.provider),class:"provider")%>,</strong>
            <p>Le <%= past_reservation.date %> à <%= past_reservation.provider.location %></p>
            <a data-action="click->comment#display" href="#" class="btn-comentaire">Laisse un commentaire!</a>
              <div class="d-none" data-comment-target="displayed">
                <%=  simple_form_for [@user, past_reservation, review] do |f| %>
                  <%= f.input :comment, label: "Commentaire" %>
                  <%= f.input :rating, label: "Note", as: :numeric , input_html: { min: '0', step: '1', max: '5', value: f.object.rating || '5' }%>
                  <%= f.button :submit, "Valider", class: 'btn btn-primary showbutton mb-3' %>
                <% end %>
              </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong> Félicitations</strong> 🎉 ta réservation est confirmée.</span>
    <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="logo">
    <%= link_to root_path do %>
      <%=image_tag "logo.png", class:"img-logo", alt:""%>
    <% end %>
  </div>
  <%= simple_form_for users_path, method: :get do %>
    <div class="product-search">
      <div class="search-element">
        <label class="search-label">Où ?</label>
        <input class="search-input" type="text" autocomplete="on" placeholder="Bordeaux" name="location">
      </div>
      <div class="search-element">
        <label class="search-label">Quel service ?</label>
        <input class="search-input" type="text" placeholder="musique" class="" autocomplete="on" name="service">
      </div>
      <div class="search-element">
        <label class="search-label">Avec qui ?</label>
        <input class="search-input" type="text" placeholder="Kevin" class="" autocomplete="on" name="provider">
      </div>
        <button type="submit" class="search-button">Rechercher</button>
    </div>
  <% end %>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to "#", class: "navbar-brand" do %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <%= image_tag "image2.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                <%= link_to " Mes réservations", user_reservations_path(current_user), class: "dropdown-item" %>
              <% else %>
                <%= link_to "Connexion", new_user_session_path, class:"dropdown-item" %>
                <%= link_to "inscription", new_user_registration_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<%= render 'shared/navbar' %>
<div class="cards">
    <% @users.each do |user| %>
      <div class="card-trip">
        <%=  cl_image_tag user.photo.key, class:"img-card", alt:"" %>
        <div class="card-trip-infos">
          <div>
           <h3><%= user.first_name %></h2>
              <p><%= user.service %>
              <br>
              <i class="fa-solid fa-trophy">:</i>
              <h2 class="card-trip-pricing"><%= user.reward %></h2>
          </div>
            <%= link_to "viens!", user_path(user), class:"btn-card" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>
<div class="cardshow col-sm- offset-sm-4">

  <div class="card-show">
    <%= cl_image_tag @user.photo.key, class:"show-photo", alt:""%>
    <div class="card-show-infos">
      <div class="service">
        <h2 class="showname"><%= @user.first_name %> <strong><%= @user.last_name %></strong></h2>
          <span class="showp"><%= @user.service %></span>
      </div>
      <div>
        <i class="fa-solid fa-trophy showicon"></i>
        <h2 class="card-trip-pricing reward"><%= @user.reward %></h2>
      </div>
    </div>
  </div>
</div>

<div class="container dateform col-sm- offset-sm-4">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <%= simple_form_for [@user, @reservation], method: :post do |f| %>
      <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder: "Quand voulez-vous réserver?" %>
      <%= f.button :submit,"Réserver", class: "btn btn-primary showbutton"%>
    <% end %>
  </div>
</div>
<% if @reviews.length != 0 %>

  <h1 class="col-sm-4 offset-sm-5">Commentaires</h1>

  <div class="commentary col-sm-6 offset-sm-3">
    <% @reviews.each do |review| %>
      <p class="showreview">Commentaire de <%= review.user.first_name %> : <%= review.comment %>
      <br><i class="fa-solid fa-star"></i> <%= review.rating%></p>
    <% end %>
  </div>
<% end %>